locals {
  mime_types = {
    "css"         = "text/css"
    "scss"        = "text/x-scss"
    "html"        = "text/html"
    "ico"         = "image/vnd.microsoft.icon"
    "js"          = "application/javascript"
    "json"        = "application/json"
    "map"         = "application/json"
    "png"         = "image/png"
    "jpg"         = "image/jpeg"
    "jpeg"        = "image/jpeg"
    "svg"         = "image/svg+xml"
    "txt"         = "text/plain"
    "woff2"       = "font/woff2"
    "woff"        = "font/woff"
    "ttf"         = "font/ttf"
    "config"      = "text/plain"
    "eot"         = "application/vnd.ms-fontobject"
    "webmanifest" = "application/manifest+json"
    "pdf"         = "application/pdf"
    "xml"         = "application/xml"
    "webp"        = "image/webp"
    "md"          = "text/plain"
    "PNG"         = "image/png"
    "stl"         = "application/vnd.ms-pki.stl"
    "mp4"         = "audio/mp4"
    "yml"         = "application/x-yaml"
    "gif"         = "image/gif"
    "tf"          = "text/plain"
    "otf"         = "font/otf"
    "JPG"         = "image/jpeg"
    "htc"         = "text/x-component"
  }
}