name: Build Jekyll site

on:
  pull_request:
    branches:
      - source
  workflow_dispatch:
  merge_group:

permissions:
  contents: read


concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup Ruby
        uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # v1.321.0
        with:
          ruby-version: '3.2'
          bundler-cache: true
          cache-version: 0
      - name: Setup ImageMagick
        uses: mfinelli/setup-imagemagick@e5a049b136cb833d5c0474b38d166f0bdb0e4497 # v7.0.1
      - name: Build with Jekyll
        run: bundle exec jekyll build
