name: Build Jekyll site

on:
  pull_request:
    branches:
      - source
  workflow_dispatch:
  merge_group:

permissions:
  contents: read


concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup Ruby
        uses: ruby/setup-ruby@354a1ad156761f5ee2b7b13fa8e09943a5e8d252 # v1.229.0
        with:
          ruby-version: '3.2'
          bundler-cache: true
          cache-version: 0
      - name: Setup ImageMagick
        uses: mfinelli/setup-imagemagick@8af1fa797580e940093cd1547349dfbb584fc908 # v6.0.1
      - name: Build with Jekyll
        run: bundle exec jekyll build
