name: Deploy Jekyll site to Pages

on:
  push:
    branches:
     - feaure/deploy-to-aws-static-hosting
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  AWS_ROLE: 'arn:aws:iam::831947081981:role/JworksTechBlogGithubRole'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Setup Ruby
        uses: ruby/setup-ruby@b203567269b5bbc256dbc1c84f7495913f977353 # v1.167.0
        with:
          ruby-version: '3.2'
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          cache-version: 0 # Increment this number if you need to re-download cached gems
      - name: Build with Jekyll
        run: bundle exec jekyll build --baseurl ""
        env:
          JEKYLL_ENV: production
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: blog
          path: _site
          if-no-files-found: error
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/create-github-app-token@2986852ad836768dfea7781f31828eb3e17990fa # v1.6.2
        id: repository-token
        with:
          app-id: ${{ vars.ORDINA_GROUP_BOT_APP_ID }}
          private-key: ${{ secrets.ORDINA_GROUP_BOT_CERT }}
          owner: ${{ github.repository_owner }}
          repositories: "jworks-aws-infra"
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Setup git creds
        run: git config --global url."https://${{ vars.ORDINA_GROUP_BOT_APP_ID }}:${{ steps.repository-token.outputs.token }}@github".insteadOf https://github
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: blog
      - name: print files
        run: ls
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@5fd3084fc36e372ff1fff382a39b10d03659f355 # v2.2.0
        with:
          role-to-assume: ${{ env.AWS_ROLE }}
          aws-region: eu-west-1
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@a1502cd9e758c50496cc9ac5308c4843bcd56d36 # v3.0.0

      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: infra/env/dev

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check
        working-directory: infra/env/dev

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        working-directory: infra/env/dev

      - name: Terraform Plan
        id: plan
        run: terraform plan
        working-directory: infra/env/dev

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve
        working-directory: infra/env/dev

