name: 'Validate Renovate config'

on:
  push:
    branches: [ "source" ]
    paths:
      - 'renovate.json'
  pull_request:
    branches: [ "source" ]
    paths:
      - 'renovate.json'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  validate-renovate-config:
    name: 'Validate Renovate config'
    runs-on: ubuntu-latest
    timeout-minutes: 5

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Setup Node.js environment
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version: '18'

      - name: Validate Renovate config
        run: npx --package renovate -c renovate-config-validator
